#!"C:\Users\ssss\AppData\Local\Programs\Python\Python38\python.exe"
# -*- coding: utf-8 -*-
"""carpredict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WDkHfTXgxlMe1w1zHD_cH11lowVtE0SG
"""

from tensorflow.keras import layers, models
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.image as img
from keras.models import load_model
import sys

def carpredict(a):

    img = Image.open('C:\\apache24\\htdocs\\search\\'+a)#.convert("L")
    img = np.resize(img, (1,28,28,3))
# 데이터를 모델에 적용할 수 있도록 가공
    test_data = ((np.array(img) / 255) - 1) * -1

# 모델 불러오기
    model = load_model('C:\\apache24\\htdocs\\Car_Model.h5')

# 클래스 예측 함수에 가공된 테스트 데이터 넣어 결과 도출
    res = model.predict(test_data, verbose =0)
#res =(model.predict(test_data) > 0.5).astype("int32")
    predicted = res.argmax(axis=-1)
    if predicted == 0 :
      predicted = '그랜저'
    if predicted == 1 :
      predicted = '쏘나타'
    if predicted == 2 :
      predicted = '아반떼'
    return predicted
tmp = carpredict("3.jpg")
print(tmp)